behaviors:
  CrumbleCupAgentRed:
    trainer_type: ppo
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

  CrumbleCupAgentBlue:
    trainer_type: ppo
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0